# Generated by Django 2.0.8 on 2018-10-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgd', '0002_auto_20180929_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog post category', 'verbose_name_plural': 'Blog post categories'},
        ),
        migrations.AlterModelOptions(
            name='postpage',
            options={'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
    ]
