# Generated by Django 2.0.8 on 2018-10-06 16:14

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pgd', '0004_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='blog_post',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_gallery_images', to='pgd.PostPage'),
        ),
    ]
