# Generated by Django 2.0.8 on 2018-10-06 16:14

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pgd', '0005_auto_20181006_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='content_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_page_gallery_images', to='pgd.ContentPage'),
        ),
    ]
