# Generated by Django 2.0.8 on 2018-10-04 19:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pgd', '0003_auto_20181004_1956'),
        ('home', '0003_homepagegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedBlogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pgd.PostPage')),
                ('post', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_blog_pages', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
