# Generated by Django 2.0.8 on 2018-10-04 19:59

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_relatedblogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedblogpage',
            name='post',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_blog_posts', to='home.HomePage'),
        ),
    ]
